In [11]:
import autograd.numpy as np
from autograd import grad

In [87]:
terms = []
X = np.zeros((9, 16))
for i in range(4):
    B = np.random.rand(3,3)
    C = np.random.rand(4,4)
    BtB = B.T.dot(B)
    CtC = C.T.dot(C)
    terms.append([BtB, CtC])
    X += np.outer(BtB.flatten(), CtC.flatten())
    
    
def dist(BtB, CtC):
    X = np.sum([np.kron(B,C) for B, C in terms])
    Y = np.kron(BtB, CtC)
    return np.sum((X-Y)**2)

def optimize():
    B = np.random.rand(3,3)
    C = np.random.rand(4,4)
    BtB = B.T.dot(B)
    CtC = C.T.dot(C)
    for i in range(10):
        BtB = np.sum([B*C.sum() for B,C in terms], axis=0) / CtC.sum()
        CtC = np.sum([C*B.sum() for B,C in terms], axis=0) / BtB.sum()
        
        scale = np.sqrt(BtB.sum() * CtC.sum())
        BtB *= scale / BtB.sum()
        CtC *= scale / CtC.sum()
        print dist(BtB, CtC)
        #print BtB, CtC
    print BtB, CtC

In [91]:
U,s,V = np.linalg.svd(X, full_matrices=False)
print X.shape, U.shape, V.shape, s.shape
S = np.diag(s)
print np.allclose(U.dot(S).dot(V),X)
print np.linalg.norm(U.dot(S).dot(V) - X)

for k in range(1, 9):
    Uk = U[:,:k]
    Vk = V[:k,:]
    Sk = np.diag(s[:k])
    print np.linalg.norm(Uk.dot(Sk).dot(Vk) - X)
    
approx = []
for i in range(2):
    BtB = U[:,i].reshape(3,3) * s[i]
    CtC = V[i,:].reshape(4,4)
    approx.append([BtB,CtC])
    
Y = np.sum([np.kron(B,C) for B, C in terms])
Z = np.sum([np.kron(B,C) for B, C in approx])
print np.sum((Y-Z)**2)


(9, 16) (9, 9) (9, 16) (9,)
True
2.02584522099e-14
1.35851813678
0.916298330789
0.412967600835
2.06489544353e-14
2.09099535322e-14
2.0872192863e-14
2.0872192863e-14
2.02584522099e-14
0.000510733154689


In [54]:
BtB = np.random.rand(3,3)
CtC = np.random.rand(4,4)
print dist(BtB, CtC)
#print grad(dist)(BtB,CtC)
optimize()

52234224.4374
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
51566864.7871
[[ 3.69736946  2.81583777  2.35289709]
 [ 2.81583777  3.97423515  2.18034707]
 [ 2.35289709  2.18034707  2.17815002]] [[ 2.05091014  1.58512835  1.84638148  1.03730919]
 [ 1.58512835  2.16694764  1.53736444  1.21813136]
 [ 1.84638148  1.53736444  2.12902107  1.23151808]
 [ 1.03730919  1.21813136  1.23151808  1.28937387]]
